services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm run dev

  json-server:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3001:3001'
    command: npm run json-server

  # storybook:
  #   image: node:18
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '6006:6006'
  #   command: npm run storybook
